#pragma once

#include <cstddef>

namespace cs2::client_dll_offsets
{

// Generated by a2x/cs2-dumper for CS2 build 14173.
inline constexpr std::ptrdiff_t kCSGOInput{0x23BA790};
inline constexpr std::ptrdiff_t kLocalPlayerPawn{0x23A5238};
inline constexpr std::ptrdiff_t kViewAngles{0x23BAE18};

inline constexpr std::ptrdiff_t kJumpButton{0x2095490};
inline constexpr std::ptrdiff_t kLeftButton{0x20952E0};
inline constexpr std::ptrdiff_t kRightButton{0x2095370};

}
