#!/usr/bin/env bash

sudo apt-get update && sudo apt-get install -y libsdl2-dev gcc-10 g++-10

mkdir Release && cd Release && cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..

make -j $(nproc --all)
