#pragma once

#include "ClientModePatternsWindows.h"
#include "ClientPatternsWindows.h"
#include "FileSystemPatternsWindows.h"
#include "GameRulesPatternsWindows.h"
#include "MemAllocPatternsWindows.h"
#include "PanelPatternsWindows.h"
#include "PanelStylePatternsWindows.h"
#include "PanoramaImagePanelPatternsWindows.h"
#include "PanoramaLabelPatternsWindows.h"
#include "PanoramaUiEnginePatternsWindows.h"
#include "PanoramaUiPanelPatternsWindows.h"
#include "PlantedC4PatternsWindows.h"
#include "SoundSystemPatternsWindows.h"
