#pragma once

#include <cstdint>

namespace csgo
{

enum class TournamentTeam : std::uint8_t {
    None = 0,
    NinjasInPyjamas = 1,
    AstanaDragons = 2,
    ComplexityGaming = 3,
    VeryGames = 4,
    IBUYPOWER = 5,
    Fnatic = 6,
    ClanMystik = 7,
    RecursiveEsports = 8,
    LGBEsports = 9,
    CopenhagenWolves = 10,
    UniversalSoldiers = 11,
    NatusVincere = 12,
    NFaculty = 13,
    SKGaming = 14,
    Xapso = 15,
    _ReasonGaming = 16,
    TeamDignitas = 24,
    HellRaisers = 25,
    TeamLDLC = 26,
    Titan = 27,
    _3DMax = 28,
    Mousesports = 29,
    ReasonGaming = 30,
    VirtusPro = 31,
    VoxEminor = 32,
    Cloud9 = 33,
    DATTeam = 34,
    EpsilonEsports = 35,
    LondonConspiracy = 36,
    TeamWolf = 37,
    MyXMG = 38,
    PENTASports = 39,
    BravadoGaming = 40,
    PlanetkeyDynamics = 41,
    ESCGaming = 42,
    Flipsid3Tactics = 43,
    TeamEnVyUs = 46,
    VexedGaming = 47,
    TeamLiquid = 48,
    CounterLogicGaming = 49,
    KeydStars = 50,
    TeamSoloMidKinguin = 51,
    Cloud9G2A = 52,
    Renegades = 53,
    TeamImmunity = 54,
    TeamKinguin = 55,
    TeamEBettle = 56,
    LuminosityGaming = 57,
    TeamSoloMid = 58,
    G2Esports = 59,
    Astralis = 60,
    FaZeClan = 61,
    Splyce = 62,
    GambitEsports = 63,
    AllStarTeamAmerica = 64,
    AllStarTeamEurope = 65,
    OpTicGaming = 66,
    GODSENT = 67,
    North = 68,
    BIG = 69,
    VegaSquadron = 70,
    Immortals = 71,
    SproutEsports = 72,
    SpaceSoldiers = 73,
    Tyloo = 74,
    Avangar = 75,
    QuantumBellatorFire = 76,
    MisfitsGaming = 77,
    _100Thieves = 78,
    FlashGaming = 79,
    MIBR = 80,
    TeamSpirit = 81,
    Rogue = 82,
    WinstrikeTeam = 83,
    ENCE = 84,
    FURIA = 85,
    GrayhoundGaming = 86,
    NRG = 87,
    ViCiGaming = 88,
    Vitality = 89,
    forZeESports = 90,
    Heroic = 95,
    OG = 96,
    EvilGeniuses = 98,
    CopenhagenFlames = 101,
    paiNGaming = 102,
    MovistarRiders = 103,
    SharksEsports = 104,
    Entropiq = 105,
    MOUZ = 106,
    IHCEsports = 108,
    Outsiders = 109,
    EternalFire = 110,
    ComplexityGaming_ = 111,
    _9ZTeam = 112,
    ImperialEsports = 113,
    BadNewsEagles = 114,
    GamerLegion = 115,
    _00Nation = 116
};

}
