name: Build and Release Shared Libraries

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build C++ Shared Library (DLL)
        run: cmake --build build --config Release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dll
          path: build/Release/*.dll

  build-linux:
    runs-on: ubuntu-24.04 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14 cmake build-essential

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        env:
          CXX: g++-14

      - name: Build C++ Shared Library (SO)
        run: cmake --build build --config Release

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-so
          path: build/*.so


  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-dll
          path: ./release-assets

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-so
          path: ./release-assets

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
